version: '3.8'

services:
  database:
    # default port 3306
    image: mysql:8
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - external-network  
  web:
    build: . # Build the image from the Dockerfile in the current directory
    container_name: yourls_python_web
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    env_file:
      - .env # Load environment variables from the .env file in the root directory
    # Optional: Add depends_on if you have a database service defined here
    # depends_on:
    #   - db 
    # Optional: Add volumes for development to reflect code changes without rebuilding
    # volumes:
    #   - ./src:/app/src
    restart: unless-stopped # Optional: Restart policy

networks:
  external-network:
    external: true
