services:
  database:
    # default port 3306
    image: mysql:8
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
    command:
      - '--default-authentication-plugin=mysql_native_password'