services:
  database:
    image: mysql:8
    restart: unless-stopped
    ports:
      - ${DB_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./.docker/mysql:/var/lib/mysql
      - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
    networks:
      - default-network  


  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8000" 
    restart: no
    command: bash -c "uv run uvicorn src.app:app --host 0.0.0.0 --port 8000 --reload --reload-dir ."
    networks:
      - default-network

networks:
  default-network:
    driver: bridge